export const FILE_DELETE_REQUEST = 'FILE_DELETE_REQUEST'
export const FILE_DELETE_SUCCESS = 'FILE_DELETE_SUCCESS'
export const FILE_DELETE_FAIL = 'FILE_DELETE_FAIL'
export const FILE_DELETE_RESET = 'FILE_DELETE_RESET'
