export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL'

export const TASK_DETAILS_REQUEST = 'TASK_DETAILS_REQUEST'
export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS'
export const TASK_DETAILS_FAIL = 'TASK_DETAILS_FAIL'

export const TASK_MY_REQUEST = 'TASK_MY_REQUEST'
export const TASK_MY_SUCCESS = 'TASK_MY_SUCCESS'
export const TASK_MY_FAIL = 'TASK_MY_FAIL'

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL'
export const TASK_CREATE_RESET = 'TASK_CREATE_RESET'

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'
export const TASK_UPDATE_RESET = 'TASK_UPDATE_RESET'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'

export const TASK_START_REQUEST = 'TASK_START_REQUEST'
export const TASK_START_SUCCESS = 'TASK_START_SUCCESS'
export const TASK_START_FAIL = 'TASK_START_FAIL'

export const TASK_SUBMIT_REQUEST = 'TASK_SUBMIT_REQUEST'
export const TASK_SUBMIT_SUCCESS = 'TASK_SUBMIT_SUCCESS'
export const TASK_SUBMIT_FAIL = 'TASK_SUBMIT_FAIL'

export const TASK_UPLOAD_REQUEST = 'TASK_UPLOAD_REQUEST'
export const TASK_UPLOAD_SUCCESS = 'TASK_UPLOAD_SUCCESS'
export const TASK_UPLOAD_FAIL = 'TASK_UPLOAD_FAIL'
export const TASK_UPLOAD_RESET = 'TASK_UPLOAD_RESET'


export const TASK_COMPLETE_REQUEST = 'TASK_COMPLETE_REQUEST'
export const TASK_COMPLETE_SUCCESS = 'TASK_COMPLETE_SUCCESS'
export const TASK_COMPLETE_FAIL = 'TASK_COMPLETE_FAIL'

export const TASK_PAY_REQUEST = 'TASK_PAY_REQUEST'
export const TASK_PAY_SUCCESS = 'TASK_PAY_SUCCESS'
export const TASK_PAY_FAIL = 'TASK_PAY_FAIL'
export const TASK_PAY_RESET = 'TASK_PAY_RESET'
